security:
    role_hierarchy:
        ROLE_ADMIN: [ ROLE_USER ]

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        fetcher:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            user_checker: App\Security\UserChecker
            custom_authenticator: App\Security\LoginFormAuthenticator
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            logout:
                path: app_logout

    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/oauth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        encoders:
            App\Security\UserIdentity: argon2i
        firewalls:
            main:
                http_basic: ~
