version: '3'

services:
    nginx:
        container_name: crud_nginx
        build:
            context: docker/development/nginx
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        ports:
            - "8088:80"
        depends_on:
            - php-fpm
            - mailer
    php-fpm:
        container_name: crud_php-fpm
        build:
            context: docker/development/php-fpm
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        depends_on:
            - database
            - mailer
    database:
        container_name: crud_database
        image: postgres:15.1-alpine
        volumes:
            - database:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54323:5432"
    mailer:
        image: mailhog/mailhog
        ports:
            - "8089:8025"

volumes:
    database:

