version: '3'

services:
    nginx:
        container_name: crud_nginx
        build:
            context: docker/development/nginx
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        ports:
            - "8088:80"
        depends_on:
            - php-fpm
    php-fpm:
        container_name: crud_php-fpm
        build:
            context: docker/development/php-fpm
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        depends_on:
            - database
    database:
        container_name: crud_database
        image: postgres:15.1-alpine
        volumes:
            - database:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: crud_db
        ports:
            - "54323:5432"

volumes:
    database:

