controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

zoom_controllers:
    resource:
        path: ../src/ZoomIntegration/Controller/
        namespace: App\ZoomIntegration\Controller
    type: attribute
